# Generated by Django 6.0 on 2025-12-26 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name_plural': 'Volunteers'},
        ),
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='cell',
        ),
        migrations.AddField(
            model_name='community',
            name='households',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='leader_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='community',
            name='population',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='province',
            field=models.CharField(choices=[('kigali', 'Kigali City'), ('south', 'Southern Province'), ('west', 'Western Province'), ('north', 'Northern Province'), ('east', 'Eastern Province')], default='kigali', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='village',
            field=models.CharField(default='unknown', help_text='Umudugudu', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='umugandaproject',
            name='community',
            field=models.ForeignKey(help_text='Select the village (Umudugudu) where this project will take place', on_delete=django.db.models.deletion.CASCADE, to='coordinator.community'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('province', 'district', 'sector', 'cell', 'village')},
        ),
    ]
