# Generated by Django 6.0 on 2025-12-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_alter_community_options_alter_volunteer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('hours_contributed', models.IntegerField(default=0)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.umugandaproject')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordinator.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'project')},
            },
        ),
    ]
